Models/DbTable.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;



namespace Asp.NetCore_MVC_Practice.Models
{
    public class DbTable
    {
        [Key]
        public int Id { get; set; }

        [Required]

        [MaxLength(20, ErrorMessage = "Name must be 20 characters only")]
        [DisplayName("Name")]
        public string? Name { get; set; } 


        [MaxLength(20,ErrorMessage = "Lastname must be 20 characters only")]
        [DisplayName("Lastname")]
        public string? Lastname { get; set; }


        [Range(1,100,ErrorMessage = "To old must be not required")]
        [DisplayName("Age")]
        public int? age { get; set; }

       
    }
}

Models/ErrorViewModel.cs
namespace Asp.NetCore_MVC_Practice.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.NetCore_MVC_Practice.Models
{
    public class Login
    {
        [Key]
        public int Id { get; set; } 
        [Required]
        public string username { get; set; }
        public string password { get; set; }    
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Asp.NetCore_MVC_Practice.Models;
using Microsoft.AspNetCore.Mvc;

namespace Asp.NetCore_MVC_Practice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {                               
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
} 

Controllers/StudentInfoController.cs
using Asp.NetCore_MVC_Practice.EntityDbData;
using Asp.NetCore_MVC_Practice.Migrations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Internal;
using System.Runtime.CompilerServices;
using Asp.NetCore_MVC_Practice.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Identity.Client;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Asp.NetCore_MVC_Practice.Controllers
{
    public class StudentInfoController : Controller
    {
        private readonly ApplicationDbContext _db;
        public StudentInfoController(ApplicationDbContext db)
        {
            _db = db;
        }

        //display data from table in html
        public IActionResult Index()
        {
            List<Models.DbTable> studentInfoList = _db.StudentInfo.ToList();
            return View(studentInfoList);
        }


        public IActionResult AddRecord()
        {
            return View();
        }

        //add record to the database
        [HttpPost]
        public IActionResult add(Models.DbTable obj)
        {
            if (ModelState.IsValid)
            {
                _db.StudentInfo.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            return View();
        }


        //para ma view yung Edit form kapag pinindot sa table yung edit
        public IActionResult Edit(int id)
        {
            var GetEdit = _db.StudentInfo.Find(id);
            return View(GetEdit);
        }


        //Edit Record to the database
        [HttpPost]
        public IActionResult Edit(Models.DbTable studentData)
        {

            var edit = _db.StudentInfo.Find(studentData.Id);


            if (edit != null)
            {
                edit.Name = studentData.Name;
                edit.Lastname = studentData.Lastname;
                edit.age = studentData.age;

                _db.SaveChanges();
            }
            return RedirectToAction("index");
        }



        [HttpPost]
        public IActionResult Delete(int id)
        {
            var record =  _db.StudentInfo.Find(id);
            if(record == null)
            {
                return NotFound();
            }
            _db.StudentInfo.Remove(record);
            _db.SaveChanges();

            return RedirectToAction("index");
        }


        [HttpPost]
        public async Task<IActionResult> Search(string Searchstring)
        {
            if (_db.StudentInfo == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }
            var names = from m in _db.StudentInfo select m;

            if (!String.IsNullOrEmpty(Searchstring))
            {
                names = names.Where(s => s.Name!.ToUpper().Contains(Searchstring.ToUpper()));
            }

            return View("index",await names.ToListAsync());

        }



    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]StudentInfo</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asp.NetCore_MVC_Practice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Info</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentInfo" asp-action="index">Student info</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() 
		</main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Asp.NetCore_MVC_Practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/StudentInfo/AddRecord.cshtml
@model DbTable


<form method="post" asp-controller="StudentInfo" asp-action="add">

	<div asp-validation-summary="All" class="validate"></div>

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Student Info</h2>
		</div>
	</div>

	<div class="mb-3">
		<label>Name</label>
		<input asp-for="Name" class="form-control"/> 
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label>Lastname</label>
		<input asp-for="Lastname" class="form-control" />
		<span asp-validation-for="Lastname" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label>Age</label>
		<input asp-for="age" class="form-control" />
		<span asp-validation-for="age" class="text-danger"></span>
	</div>
	


    <div class="row">
		
	<div class="col-6">
	<button type="submit" class="btn btn-primary form-control">Add Student</button>
    </div>

	<div class="col-6">
	<a asp-controller="StudentInfo" asp-action="index" class="btn btn-end form-control">Back</a>
	</div>

	</div>




	</div>

</form>


@*for realtime validation gamit jquery*@
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/StudentInfo/Edit.cshtml
@model DbTable

<form method="post">

	<div asp-validation-summary="All" class="validate"></div>

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Student Info</h2>
		</div>
	</div>

	<div class="mb-3">
		<label>Name</label>
		<input asp-for="Name" class="form-control" />
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label>Lastname</label>
		<input asp-for="Lastname" class="form-control" />
		<span asp-validation-for="Lastname" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label>Age</label>
		<input asp-for="age" class="form-control" />
		<span asp-validation-for="age" class="text-danger"></span>
	</div>

	<div class="row">
		<div class="col-6">
			<button type="submit" class="btn btn-primary form-control">Update Student</button>
		</div>
		<div class="col-6">
			<a asp-controller="StudentInfo" asp-action="index" class="btn btn-secondary form-control">Back</a>
		</div>
	</div>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Views/StudentInfo/index.cshtml
@{
	ViewData["Title"] = "Student Info";
}
@model List<DbTable>





<form asp-controller="StudentInfo" asp-action="Search" method="post">
	<input type="text" name="Searchstring"/>
	<input type="submit" value="Search" />
</form>



<div class="container">

	<div class="row pt-4">
		<div class="col-6"><h1 class="text-primary">Student List</h1></div>
		<div class="col-6 text-end"><a asp-controller="StudentInfo" asp-action="AddRecord" class="btn btn-primary">Add record</a></div>
	</div>

<table class="table">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Id</th>
			<th scope="col">Name</th>
			<th scope="col">Lastname</th>
			<th scope="col">age</th>
		</tr>
	</thead>
	<tbody>
		@foreach(DbTable info in Model){
			<tr>
				<td>@info.Id</td>
				<td>@info.Name</td>
				<td>@info.Lastname</td>
				<td>@info.age</td>
				<td><a asp-controller="StudentInfo" asp-route-id ="@info.Id" asp-action="Edit">Edit</a></td>

			    <td>
					<form asp-controller="StudentInfo" asp-action="Delete" asp-route-Id="@info.Id" method="post">
					   <button type="submit" class="btn btn-danger btn-sm">Delete</button>
				    </form>
				</td>
			</tr>
		}
	</tbody>
</table>


</div>